version: '3'

services:

  api:
    build: ./
    ports:
     - 3000:3000
    depends_on:
      - mongodb
    environment:
      MONGODB_URI: mongodb://mongodb:27017/backboil
    command: [ "npm", "run", "service:api" ]

  test:
    build: ./
    command: [ "npm", "test" ]

  mongodb:
    image: mongo:latest
    ports:
        - 27017:27017

  redis:
    image: redis:4.0.2
    volumes:
      - ./data/db/redis:/data
    ports:
      - 6379:6379
